"""add_session_tracking

Revision ID: 07bc7d2b2b3f
Revises: c1f71e217bc9
Create Date: 2025-10-10 16:01:49.486576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bc7d2b2b3f'
down_revision: Union[str, Sequence[str], None] = 'c1f71e217bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
