"""Added level_field to the problems.

Revision ID: 2e978d32d75b
Revises: 6e20ab88ddbb
Create Date: 2025-09-28 14:43:16.708380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e978d32d75b'
down_revision: Union[str, Sequence[str], None] = '6e20ab88ddbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'level')
    # ### end Alembic commands ###
