"""add_forum_approval_field

Revision ID: 6e1d515b6686
Revises: 64d11b9b6b28
Create Date: 2025-10-10 16:38:46.117262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1d515b6686'
down_revision: Union[str, Sequence[str], None] = '64d11b9b6b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forums', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forums', 'is_approved')
    # ### end Alembic commands ###
