"""add updated_at field to ProblemResponse and CommentResponse

Revision ID: 6e20ab88ddbb
Revises: e66194bbd448
Create Date: 2025-09-28 14:19:49.486341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e20ab88ddbb'
down_revision: Union[str, Sequence[str], None] = 'e66194bbd448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('problems', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'updated_at')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
