"""add_push_notifications_to_notification_preferences

Revision ID: 727faa180945
Revises: 6e1d515b6686
Create Date: 2025-10-10 17:40:31.389131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727faa180945'
down_revision: Union[str, Sequence[str], None] = '6e1d515b6686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('push_likes', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_comments', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_follows', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_forum_invitations', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_forum_join_requests', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('push_forum_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'push_forum_deleted')
    op.drop_column('notification_preferences', 'push_forum_join_requests')
    op.drop_column('notification_preferences', 'push_forum_invitations')
    op.drop_column('notification_preferences', 'push_follows')
    op.drop_column('notification_preferences', 'push_comments')
    op.drop_column('notification_preferences', 'push_likes')
    # ### end Alembic commands ###
