"""add_forum_problems_changes

Revision ID: 729592004c17
Revises: e7567357284e
Create Date: 2025-10-05 23:44:41.213748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729592004c17'
down_revision: Union[str, Sequence[str], None] = 'e7567357284e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('forum_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problems', 'forums', ['forum_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'forum_id')
    # ### end Alembic commands ###
