"""fix forum_message problem_id foreign key

Revision ID: 9440fc2fdfbc
Revises: 729592004c17
Create Date: 2025-10-06 00:15:13.751090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9440fc2fdfbc'
down_revision: Union[str, Sequence[str], None] = '729592004c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint
    op.drop_constraint(op.f('forum_messages_problem_id_fkey'), 'forum_messages', type_='foreignkey')
    # Then drop the table
    op.drop_index(op.f('ix_forum_problems_id'), table_name='forum_problems')
    op.drop_table('forum_problems')
    # Finally create the new foreign key constraint
    op.create_foreign_key(None, 'forum_messages', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_messages', type_='foreignkey')
    op.create_foreign_key(op.f('forum_messages_problem_id_fkey'), 'forum_messages', 'forum_problems', ['problem_id'], ['id'])
    op.create_table('forum_problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forum_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('forum_problems_author_id_fkey')),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], name=op.f('forum_problems_forum_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_problems_pkey'))
    )
    op.create_index(op.f('ix_forum_problems_id'), 'forum_problems', ['id'], unique=False)
    # ### end Alembic commands ###
