"""add_is_banned_to_forum_membership

Revision ID: 95058c92388b
Revises: 9881a21d224e
Create Date: 2025-10-08 16:20:40.763527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95058c92388b'
down_revision: Union[str, Sequence[str], None] = '9881a21d224e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_memberships', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_memberships', 'is_banned')
    # ### end Alembic commands ###
