"""add_is_pinned_to_forum_messages

Revision ID: 9881a21d224e
Revises: f040679bcf4d
Create Date: 2025-10-08 14:17:36.694807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9881a21d224e'
down_revision: Union[str, Sequence[str], None] = 'f040679bcf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_messages', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_messages', 'is_pinned')
    # ### end Alembic commands ###
