"""add_is_solution_to_comments

Revision ID: b83d8f88c738
Revises: dffca639c6f7
Create Date: 2025-10-07 12:43:50.562315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83d8f88c738'
down_revision: Union[str, Sequence[str], None] = 'dffca639c6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_solution', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_solution')
    # ### end Alembic commands ###
