"""add_report_assignment_and_user_history

Revision ID: c1f71e217bc9
Revises: 6d999da9f19d
Create Date: 2025-10-09 22:11:21.614473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f71e217bc9'
down_revision: Union[str, Sequence[str], None] = '6d999da9f19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_reports', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('site_reports', sa.Column('investigation_notes', sa.Text(), nullable=True))
    op.add_column('site_reports', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('site_reports', sa.Column('email_content', sa.Text(), nullable=True))
    op.add_column('site_reports', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'site_reports', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_reports', type_='foreignkey')
    op.drop_column('site_reports', 'email_sent_at')
    op.drop_column('site_reports', 'email_content')
    op.drop_column('site_reports', 'email_sent')
    op.drop_column('site_reports', 'investigation_notes')
    op.drop_column('site_reports', 'assigned_to')
    # ### end Alembic commands ###
