"""add_forum_messages_table

Revision ID: c4afaebe45cd
Revises: ca7eeb90d38a
Create Date: 2025-10-04 13:33:46.503562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4afaebe45cd'
down_revision: Union[str, Sequence[str], None] = 'ca7eeb90d38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
