"""add_forum_badges

Revision ID: dffca639c6f7
Revises: 255e5fe178ee
Create Date: 2025-10-07 01:18:01.924341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffca639c6f7'
down_revision: Union[str, Sequence[str], None] = '255e5fe178ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forums', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('forums', sa.Column('level', sa.String(), nullable=True))
    op.add_column('forums', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forums', 'tags')
    op.drop_column('forums', 'level')
    op.drop_column('forums', 'subject')
    # ### end Alembic commands ###
