"""add_forum_notifications

Revision ID: e7567357284e
Revises: ff3b2acba0f7
Create Date: 2025-10-05 22:47:12.959614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7567357284e'
down_revision: Union[str, Sequence[str], None] = 'ff3b2acba0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('email_forum_invitations', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('email_forum_join_requests', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('email_forum_deleted', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('in_app_forum_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'in_app_forum_deleted')
    op.drop_column('notification_preferences', 'email_forum_deleted')
    op.drop_column('notification_preferences', 'email_forum_join_requests')
    op.drop_column('notification_preferences', 'email_forum_invitations')
    # ### end Alembic commands ###
