"""add_typing_fields_to_user_online

Revision ID: f040679bcf4d
Revises: ab528383d036
Create Date: 2025-10-07 23:22:53.676478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f040679bcf4d'
down_revision: Union[str, Sequence[str], None] = 'ab528383d036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_online_status', sa.Column('is_typing', sa.Boolean(), nullable=True))
    op.add_column('user_online_status', sa.Column('last_typing', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_online_status', 'last_typing')
    op.drop_column('user_online_status', 'is_typing')
    # ### end Alembic commands ###
