"""add_data_field_to_notification

Revision ID: ff3b2acba0f7
Revises: c6f85caad0bf
Create Date: 2025-10-04 21:29:34.298614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3b2acba0f7'
down_revision: Union[str, Sequence[str], None] = 'c6f85caad0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'data')
    # ### end Alembic commands ###
